title: Music and Science Book
description: Python notebooks for interactive sessions on analysing audio and music
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one