# theme: Minimal Mistakes
remote_theme: mmistakes/minimal-mistakes@4.18.1
minimal_mistakes_skin: default
plugins:
  - jekyll-include-cache
#  - jekyll-optional-front-matter

# directories
plugins_dir: pages/plugins
layouts_dir: pages/layouts
data_dir: pages/data
includes_dir: pages/includes
sass_dir: pages/sass
empress_dir: pages/empress

# metadata
title: Music and Science – Guide to Empirical Music Research
# subtitle: Ver 1.0
name: Tuomas Eerola
description: Jupyter notebooks for for analysing audio and music
url: https://tuomaseerola.github.io/emr/
logo: ../gallery/MusicScienceDU.png
locale: en-UK

# features:
# search: true
permalink: none

# default
defaults:
  - scope:
      path: ''
      type: pages
    values:
      title: ''
      # author_profile: true
      layout: single
      # toc: true
      # toc_sticky: true
      classes: wide
      sidebar:
         nav: false
      # comments: true
      share: false
      # related: true

# footer
footer:
  links:
    - label: License
      icon: fas fa-fw fa-certificate
      url: LICENSE
      description: 'BSD 3-Clause'
    - label: Citation
      icon: fas fa-fw fa-book
      url: https://tuomaseerola.github.io/emr/citation.html
      description: 'Citation in APA and Bibtex formats'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://tuomaseerola.github.io/emr/
      description: 'tuomaseerola/emr'
    - label: Twitter
      icon: fab fa-fw fa-twitter
      url: https://twitter.com/tuomas_ee
      description: '@tuomas_ee'
    - label: Contact
      icon: fas fa-fw fa-envelope
      url: mailto:tuomas.eerola@durham.ac.uk
      description: 'email'