# rename_variables.R
# Part of R_template by Tuomas Eerola, https://github.com/tuomaseerola/R_template/

# Note. This is unusually extensive renaming of the variables as the variables have not 
# been coded in the Qualtrics. 

#### 1. Rename variable headers ---------------------------------------------------
colnames(v)[colnames(v)=="Duration..in.seconds."]<-"Time"
colnames(v)[colnames(v)=="Q3"]<-"Age"
colnames(v)[colnames(v)=="Q4"]<-"Gender"
colnames(v)[colnames(v)=="Q5"]<-"Country"
colnames(v)[colnames(v)=="Q6"]<-"MusicalExpertise"
colnames(v)[colnames(v)=="Q7"]<-"PreferredGenre"
colnames(v)[colnames(v)=="Q8"]<-"InstrumentPlayer"
colnames(v)[colnames(v)=="Q9"]<-"Instrument"
colnames(v)[colnames(v)=="Q10"]<-"MusicalTraining"

# Note:
# Track rating renamed, where OG = original track and PT = participants' track
# Middle number is number of track, and emotion names at end are the different emotion rating scales

colnames(v)[colnames(v)=="Q14_1"]<-"OG_01_SADNESS"
colnames(v)[colnames(v)=="Q14_2"]<-"OG_01_CALMNESS"
colnames(v)[colnames(v)=="Q14_3"]<-"OG_01_JOY"
colnames(v)[colnames(v)=="Q14_4"]<-"OG_01_ANGER"
colnames(v)[colnames(v)=="Q14_5"]<-"OG_01_FEAR"
colnames(v)[colnames(v)=="Q14_6"]<-"OG_01_POWER"
colnames(v)[colnames(v)=="Q14_7"]<-"OG_01_SURPRISE"

colnames(v)[colnames(v)=="Q15_1"]<-"OG_02_SADNESS"
colnames(v)[colnames(v)=="Q15_2"]<-"OG_02_CALMNESS"
colnames(v)[colnames(v)=="Q15_3"]<-"OG_02_JOY"
colnames(v)[colnames(v)=="Q15_4"]<-"OG_02_ANGER"
colnames(v)[colnames(v)=="Q15_5"]<-"OG_02_FEAR"
colnames(v)[colnames(v)=="Q15_6"]<-"OG_02_POWER"
colnames(v)[colnames(v)=="Q15_7"]<-"OG_02_SURPRISE"

colnames(v)[colnames(v)=="Q16_1"]<-"OG_03_SADNESS"
colnames(v)[colnames(v)=="Q16_2"]<-"OG_03_CALMNESS"
colnames(v)[colnames(v)=="Q16_3"]<-"OG_03_JOY"
colnames(v)[colnames(v)=="Q16_4"]<-"OG_03_ANGER"
colnames(v)[colnames(v)=="Q16_5"]<-"OG_03_FEAR"
colnames(v)[colnames(v)=="Q16_6"]<-"OG_03_POWER"
colnames(v)[colnames(v)=="Q16_7"]<-"OG_03_SURPRISE"

colnames(v)[colnames(v)=="Q17_1"]<-"OG_04_SADNESS"
colnames(v)[colnames(v)=="Q17_2"]<-"OG_04_CALMNESS"
colnames(v)[colnames(v)=="Q17_3"]<-"OG_04_JOY"
colnames(v)[colnames(v)=="Q17_4"]<-"OG_04_ANGER"
colnames(v)[colnames(v)=="Q17_5"]<-"OG_04_FEAR"
colnames(v)[colnames(v)=="Q17_6"]<-"OG_04_POWER"
colnames(v)[colnames(v)=="Q17_7"]<-"OG_04_SURPRISE"

colnames(v)[colnames(v)=="Q18_1"]<-"OG_05_SADNESS"
colnames(v)[colnames(v)=="Q18_2"]<-"OG_05_CALMNESS"
colnames(v)[colnames(v)=="Q18_3"]<-"OG_05_JOY"
colnames(v)[colnames(v)=="Q18_4"]<-"OG_05_ANGER"
colnames(v)[colnames(v)=="Q18_5"]<-"OG_05_FEAR"
colnames(v)[colnames(v)=="Q18_6"]<-"OG_05_POWER"
colnames(v)[colnames(v)=="Q18_7"]<-"OG_05_SURPRISE"

colnames(v)[colnames(v)=="Q19_1"]<-"OG_06_SADNESS"
colnames(v)[colnames(v)=="Q19_2"]<-"OG_06_CALMNESS"
colnames(v)[colnames(v)=="Q19_3"]<-"OG_06_JOY"
colnames(v)[colnames(v)=="Q19_4"]<-"OG_06_ANGER"
colnames(v)[colnames(v)=="Q19_5"]<-"OG_06_FEAR"
colnames(v)[colnames(v)=="Q19_6"]<-"OG_06_POWER"
colnames(v)[colnames(v)=="Q19_7"]<-"OG_06_SURPRISE"

colnames(v)[colnames(v)=="Q20_1"]<-"OG_07_SADNESS"
colnames(v)[colnames(v)=="Q20_2"]<-"OG_07_CALMNESS"
colnames(v)[colnames(v)=="Q20_3"]<-"OG_07_JOY"
colnames(v)[colnames(v)=="Q20_4"]<-"OG_07_ANGER"
colnames(v)[colnames(v)=="Q20_5"]<-"OG_07_FEAR"
colnames(v)[colnames(v)=="Q20_6"]<-"OG_07_POWER"
colnames(v)[colnames(v)=="Q20_7"]<-"OG_07_SURPRISE"

colnames(v)[colnames(v)=="Q21_1"]<-"PT_01_SADNESS"
colnames(v)[colnames(v)=="Q21_2"]<-"PT_01_CALMNESS"
colnames(v)[colnames(v)=="Q21_3"]<-"PT_01_JOY"
colnames(v)[colnames(v)=="Q21_4"]<-"PT_01_ANGER"
colnames(v)[colnames(v)=="Q21_5"]<-"PT_01_FEAR"
colnames(v)[colnames(v)=="Q21_6"]<-"PT_01_POWER"
colnames(v)[colnames(v)=="Q21_7"]<-"PT_01_SURPRISE"

colnames(v)[colnames(v)=="Q22_1"]<-"PT_02_SADNESS"
colnames(v)[colnames(v)=="Q22_2"]<-"PT_02_CALMNESS"
colnames(v)[colnames(v)=="Q22_3"]<-"PT_02_JOY"
colnames(v)[colnames(v)=="Q22_4"]<-"PT_02_ANGER"
colnames(v)[colnames(v)=="Q22_5"]<-"PT_02_FEAR"
colnames(v)[colnames(v)=="Q22_6"]<-"PT_02_POWER"
colnames(v)[colnames(v)=="Q22_7"]<-"PT_02_SURPRISE"

colnames(v)[colnames(v)=="Q23_1"]<-"PT_03_SADNESS"
colnames(v)[colnames(v)=="Q23_2"]<-"PT_03_CALMNESS"
colnames(v)[colnames(v)=="Q23_3"]<-"PT_03_JOY"
colnames(v)[colnames(v)=="Q23_4"]<-"PT_03_ANGER"
colnames(v)[colnames(v)=="Q23_5"]<-"PT_03_FEAR"
colnames(v)[colnames(v)=="Q23_6"]<-"PT_03_POWER"
colnames(v)[colnames(v)=="Q23_7"]<-"PT_03_SURPRISE"

colnames(v)[colnames(v)=="Q24_1"]<-"PT_04_SADNESS"
colnames(v)[colnames(v)=="Q24_2"]<-"PT_04_CALMNESS"
colnames(v)[colnames(v)=="Q24_3"]<-"PT_04_JOY"
colnames(v)[colnames(v)=="Q24_4"]<-"PT_04_ANGER"
colnames(v)[colnames(v)=="Q24_5"]<-"PT_04_FEAR"
colnames(v)[colnames(v)=="Q24_6"]<-"PT_04_POWER"
colnames(v)[colnames(v)=="Q24_7"]<-"PT_04_SURPRISE"

colnames(v)[colnames(v)=="Q25_1"]<-"PT_05_SADNESS"
colnames(v)[colnames(v)=="Q25_2"]<-"PT_05_CALMNESS"
colnames(v)[colnames(v)=="Q25_3"]<-"PT_05_JOY"
colnames(v)[colnames(v)=="Q25_4"]<-"PT_05_ANGER"
colnames(v)[colnames(v)=="Q25_5"]<-"PT_05_FEAR"
colnames(v)[colnames(v)=="Q25_6"]<-"PT_05_POWER"
colnames(v)[colnames(v)=="Q25_7"]<-"PT_05_SURPRISE"

colnames(v)[colnames(v)=="Q26_1"]<-"PT_06_SADNESS"
colnames(v)[colnames(v)=="Q26_2"]<-"PT_06_CALMNESS"
colnames(v)[colnames(v)=="Q26_3"]<-"PT_06_JOY"
colnames(v)[colnames(v)=="Q26_4"]<-"PT_06_ANGER"
colnames(v)[colnames(v)=="Q26_5"]<-"PT_06_FEAR"
colnames(v)[colnames(v)=="Q26_6"]<-"PT_06_POWER"
colnames(v)[colnames(v)=="Q26_7"]<-"PT_06_SURPRISE"

colnames(v)[colnames(v)=="Q27_1"]<-"PT_07_SADNESS"
colnames(v)[colnames(v)=="Q27_2"]<-"PT_07_CALMNESS"
colnames(v)[colnames(v)=="Q27_3"]<-"PT_07_JOY"
colnames(v)[colnames(v)=="Q27_4"]<-"PT_07_ANGER"
colnames(v)[colnames(v)=="Q27_5"]<-"PT_07_FEAR"
colnames(v)[colnames(v)=="Q27_6"]<-"PT_07_POWER"
colnames(v)[colnames(v)=="Q27_7"]<-"PT_07_SURPRISE"
